### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lneuhaus** [lneuhaus/pyrpl#284]
conda install python=3.5
conda install pyqt=4
conda install numpy
conda install pandas
conda install scipy
pip install scp

**Comment by lneuhaus** [comment]
hmm. So far we are not using pandas, but it is really practical and not so slow imho. Especially the dataframe should be reconsidered i think. The big changes of the pandas API that we experienced a few years ago were because (I think) Continuum Analytics started to professionally polish the repository for data science. I do believe the code now has a large user community which would be equally unhappy to see API changes. So I deem it unlikely that we will run into problems. Or are there other problems with pandas that I am not aware of?

**Comment by SamuelDeleglise** [comment]
I fully agree that we should allow for storing "multichannel curves" for instance for (time, channel1, channel2), or (frequency, spectrum1, spectrum2, cross_spectrum), which is the purpose of the dataframe, but in principle this would be possible with multidimensional numpy array.

I just got very frustrated by pandas because of:
1.  the changes of API. 
2. Also because it was the hardest dependency to install (especially with pytables...). 
3. Also I frequently ran into problems with the index type. Things work smoothly as long as the index type is Float64Index, but for some reason that I never fully understood, the index would change to 'object'. Maybe that's just a simple problem in my code, but I am not sure...

If you really believe these problems are behind us, then maybe we can go for it...

**Comment by lneuhaus** [comment]
Api changes should be ok

Installation is straightforward with conda

I never had problems with np.asarray(series.index.values, dtype=np.float)

**Comment by SamuelDeleglise** [comment]
OK, but I find it weird that most of the time series.index is working fine, but in rare occasions, it becomes an array of 'object' which leads to very cryptic error messages (especially for inexperienced users).

**Comment by lneuhaus** [comment]
Maybe reproduce and file an issue on pandas repo in github?
