### ISSUE TITLE
Windows binary for 32-bit Windows 7 available?

### ISSUE THREAD

**Issue by seanmossman** [lneuhaus/pyrpl#345]
Hey, thanks for the great work on this system! I'm trying to get the windows binary pyrpl-windows.exe running on a 32-bit Windows 7 machine and I'm getting an error message indicating incompatibility. Is there a version of the .exe which is compatible with my system? Thanks again!

**Comment by lneuhaus** [comment]
Hi, 
in principle Pyrpl should run on Win32 systems. 

The file pyrpl-windows.exe was automatically generated on a 64bit machine provided by AppVeyor. They do not have win32-images in their portfolio, which is why we only have 64bit versions. I personally also do not have a win32 machine. 

In principle, one could however generate such a win32.exe, given any available win32 machine. Two options:
1. A continuous integration service such as AppVeyor appears that gives us access to Win32 systems. So far, I am not aware that one (free) service exists. 
2. You try to run Pyrpl from source code. If you really want a binary, you can follow the instructions available below to generate one on your system: https://pyrpl.readthedocs.io/en/latest/developer_guide/dist/executable.html

Sorry I cant help you with less effort. If someone is around here with a Win32-System, would you mind to run the instructions of above link?
